### ISSUE TITLE
[ERROR] GiveNextWeapon: cant get player for slot

### ISSUE THREAD

**Issue by stonenightcode** [ssypchenko/cs2-gungame#1]
I get a lot of exceptions in my server log. The Problem is, that the players do not get a new weapon. Level is not increased.

`02:16:58 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GunGame.GunGame.ForgiveShots(Int32 client) in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 2733
   at GunGame.GunGame.EventPlayerDeathHandler(EventPlayerDeath event, GameEventInfo info) in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 942
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
`
  
  `
  [ERROR] GiveNextWeapon: cant get player for slot 3
02:21:56 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GunGame.GunGame.ForgiveShots(Int32 client) in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 2733
   at GunGame.GunGame.EventPlayerDeathHandler(EventPlayerDeath event, GameEventInfo info) in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 942
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
CNavMesh::TestRayToMesh error.  Ray did not exit nav area.
`
`
[ERROR] GiveNextWeapon: cant get player for slot 10
02:22:36 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GunGame.GunGame.ForgiveShots(Int32 client) in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 2733
   at GunGame.GunGame.EventPlayerDeathHandler(EventPlayerDeath event, GameEventInfo info) in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 942
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82`

**Comment by ssypchenko** [comment]
Hi,

Tomorrow I will have limited access to my computer. I’ll try to check what
may happen on your side on Sunday.

**Comment by stonenightcode** [comment]
Thanks a lot!

**Comment by ssypchenko** [comment]
As I understand, the problem is that I define the array like 
g_Shot = new bool[64,64];
but then I scan it like 
for (int vict = 0; vict <= Server.MaxPlayers; vict++)

So if the "Server.MaxPlayers" is more than 63 on your server, it may cause the problem 
What is the value of Server.MaxPlayers on your server? 
Maybe I just need to increase the array size...

**Comment by stonenightcode** [comment]
But I had the same issues on Servers with only 10 Players.

Max Players was 64 but you start counting from zero so 63 should be enough?

**Comment by ssypchenko** [comment]
> But I had the same issues on Servers with only 10 Players.
> 
> Max Players was 64 but you start counting from zero so 63 should be enough?

Could you please check if you have the same error on the new version (1.0.3)?

**Comment by stonenightcode** [comment]
Thanks a lot this problem seems to be fixed and I don't get exceptions in the server log anymore.

But now I have an other issue. I will oben a separate one.
