### ISSUE TITLE
Error in console every time I kill a bot

### ISSUE THREAD

**Issue by kus** [ssypchenko/cs2-gungame#17]
Using latest Metamod, CounterStrikeSharp and your plugin.

```
] meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (v246 @ a87bd25) by Roflmuffin
```

```
] css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 11 plugins loaded.
  [#1:UNLOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl
    Allows for server commands to be executed from the client using !rcon
  [#2:LOADED]: "RockTheVote" (1.8.5) by abnerfs
    https://github.com/abnerfs/cs2-rockthevote
  [#3:LOADED]: "Custom Votes" (1.0.1) by imi-tat0r
    Allows you to create custom votes for your server.
  [#4:LOADED]: "SimpleAdmin" (0.1.2)
  [#5:LOADED]: "GameModeManager" (1.0.4) by Striker-Nick
    A simple plugin to help administrators manage custom game modes, settings, and map rotations.
  [#6:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory
    Allow server owners to easily create unique configuration files on a per map basis.
  [#7:LOADED]: "CS2 Announcement Broadcaster" (0.3.0) by Lengran
    A plugin that helps server admins to broadcast announcements to users. https://github.com/lengran/CS2AnnouncementBroadcaster
  [#8:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)
    Executes a command after server event or a delay. exec_after for help
  [#9:LOADED]: "CS2_GunGame" (v1.1.2) by Sergey
    GunGame mode for CS2
  [#10:LOADED]: "Remove Map Weapons" (1.0.1) by Kus (https://github.com/kus)
    Remove the weapons from the map
```

The errors in the server console:

```
Kus killed Operator with awp
03:15:24 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 77
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at GunGame.GunGame.<>c__DisplayClass163_1.<Respawn>b__0() in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 3983
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
Operator killed Kus with awp
03:15:33 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 77
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at GunGame.GunGame.<>c__DisplayClass163_1.<Respawn>b__0() in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 3983
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
Operator killed Kus with negev
03:15:39 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 77
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at GunGame.GunGame.<>c__DisplayClass163_1.<Respawn>b__0() in /Users/sergeysypchenko/css-development/GG2/gg2.cs:line 3983
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by ssypchenko** [comment]
Hopefully, new CSS updates had fixed that.
